import React, { useState, useCallback, useRef } from "react";
import {
  Modal, View, Text, TextInput, TouchableOpacity,
  ScrollView, Linking, Alert, ActivityIndicator, StyleSheet,
} from "react-native";
import { Feather } from "@expo/vector-icons";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useColors } from "@/hooks/useColors";
import { useApp } from "@/context/AppContext";
import * as Haptics from "expo-haptics";
import * as Clipboard from "expo-clipboard";
import {
  createRepo, pushFiles, enablePages, makeRepoPublic,
  getUser, getRepoTree, getFileContent, dispatchWorkflow,
} from "@/services/githubService";

interface Props {
  visible: boolean;
  onClose: () => void;
}

type Phase = "input" | "analyzing" | "review" | "building" | "done" | "error";
type BuildMethod = "capacitor-web" | "eas-cloud" | "capacitor-vite" | "capacitor-expo";

interface GeneratedFile {
  path: string;
  content: string;
  label: string;
}

interface Analysis {
  method: BuildMethod;
  appName: string;
  repoOwner: string;
  repoName: string;
  packageId: string;
  themeColor: string;
  reason: string;
  generated: GeneratedFile[];    // files auto-generated by the builder
  existing: string[];            // files already in the repo (not replaced)
  allFiles: Array<{ path: string; content: string }>;
}

// ─────────────────────────────────────────────────────────────────────────────
// Utils
// ─────────────────────────────────────────────────────────────────────────────

function sanitize(s: string) {
  return s.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
}
function toPackageId(owner: string, repo: string) {
  const o = (owner || "com").replace(/[^a-z0-9]/gi, "").toLowerCase().slice(0, 20) || "com";
  const r = (repo || "app").replace(/[^a-z0-9]/g, "").slice(0, 20) || "app";
  return `com.${o}.${r}`;
}
function parseGithubUrl(input: string): { owner: string; repo: string } | null {
  const clean = input.trim().replace(/\.git$/, "");
  const m =
    clean.match(/github\.com[/:]([\w.-]+)\/([\w.-]+)/) ||
    clean.match(/^([\w.-]+)\/([\w.-]+)$/);
  if (m) return { owner: m[1], repo: m[2] };
  return null;
}
function extractColor(html: string): string {
  const m = html.match(/theme-color["']?\s+content=["']([#\w]+)/i) ||
            html.match(/background[_-]?color["']?\s*[:=]\s*["']([#\w]+)/i);
  return m?.[1] || "#0d1117";
}

// ─────────────────────────────────────────────────────────────────────────────
// File generators
// ─────────────────────────────────────────────────────────────────────────────

function genManifest(appName: string, themeColor: string): string {
  const short = appName.split(/\s+/)[0].slice(0, 12);
  return JSON.stringify({
    name: appName,
    short_name: short,
    start_url: "./",
    display: "standalone",
    orientation: "portrait",
    background_color: themeColor,
    theme_color: themeColor,
    icons: [
      { src: "icon.svg", sizes: "any", type: "image/svg+xml", purpose: "any maskable" },
    ],
  }, null, 2);
}

function genIconSvg(appName: string, themeColor: string): string {
  const initial = (appName || "A").charAt(0).toUpperCase();
  // pick a good contrasting text color
  const bg = themeColor.replace("#", "");
  const r = parseInt(bg.slice(0, 2), 16) || 13;
  const g = parseInt(bg.slice(2, 4), 16) || 17;
  const b = parseInt(bg.slice(4, 6), 16) || 23;
  const lum = 0.299 * r + 0.587 * g + 0.114 * b;
  const fg = lum > 128 ? "#000000" : "#ffffff";
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 192 192">
  <rect width="192" height="192" rx="32" fill="${themeColor}"/>
  <text x="96" y="130" font-family="Arial,sans-serif" font-weight="bold"
    font-size="100" text-anchor="middle" fill="${fg}">${initial}</text>
</svg>`;
}

function genServiceWorker(): string {
  return `// Service Worker — gerado pelo DevMobile
const CACHE = 'app-v1';
const ASSETS = ['./', './index.html'];

self.addEventListener('install', e =>
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(ASSETS)))
);
self.addEventListener('fetch', e =>
  e.respondWith(
    caches.match(e.request).then(r => r || fetch(e.request))
  )
);
`;
}

function genCapacitorConfig(appName: string, packageId: string, webDir: string): string {
  return JSON.stringify({
    appId: packageId,
    appName: appName,
    webDir: webDir,
    server: { androidScheme: "https" },
    android: { allowMixedContent: false },
  }, null, 2);
}

// ─── GitHub Actions workflows ──────────────────────────────────────────────

/** Capacitor workflow — usado para HTML/JS e apps Vite buildados.
 *  Resolve os erros de Gradle usando android-actions/setup-android
 *  e versões fixas do Capacitor em vez do Bubblewrap. */
function genCapacitorWorkflow(
  appName: string,
  packageId: string,
  themeColor: string,
  webDir: string,
  preBuildCmd?: string,
): string {
  const initial = (appName || "A").charAt(0).toUpperCase();
  const wd = webDir === "." ? "" : `${webDir}/`;
  const gradleDir = webDir === "." ? "android" : `${webDir}/android`;

  return `name: "\uD83E\uDD16 Build APK Android"
on:
  workflow_dispatch:
  push:
    branches: [main, master]
permissions:
  contents: write
env:
  APP_NAME: "${appName.replace(/"/g, '\\"')}"
  PACKAGE_ID: "${packageId}"
  THEME_COLOR: "${themeColor}"
jobs:
  build-apk:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: temurin

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
${preBuildCmd ? `
      - name: Instalar dependencias e buildar
        run: |
          ${preBuildCmd}
` : ""}
      - name: Gerar icones com ImageMagick
        run: |
          sudo apt-get install -y imagemagick -q 2>/dev/null
          INIT="${initial}"
          FONT="/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
          [ -f "$FONT" ] || FONT="DejaVu-Sans-Bold"
          gen_icon() {
            SZ=$1; OUT=$2
            convert -size ${SZ}x${SZ} xc:"$THEME_COLOR" \\
              -fill white -font "$FONT" \\
              -pointsize $((SZ / 2)) -gravity center \\
              -annotate 0 "$INIT" "$OUT" 2>/dev/null || \\
            convert -size ${SZ}x${SZ} xc:"$THEME_COLOR" \\
              -fill white -pointsize $((SZ / 2)) -gravity center \\
              -draw "text 0,0 '$INIT'" "$OUT" 2>/dev/null || true
          }
          gen_icon 192 ${wd}icon-192.png
          gen_icon 512 ${wd}icon-512.png
          echo "Icones gerados"

      - name: Gerar keystore de assinatura
        run: |
          keytool -genkey -v \\
            -keystore release.keystore -alias app \\
            -keyalg RSA -keysize 2048 -validity 10000 \\
            -storepass android123 -keypass android123 \\
            -dname "CN=$APP_NAME, OU=App, O=DevMobile, L=BR, ST=SP, C=BR"

      - name: Instalar Capacitor (versoes fixas)
        working-directory: ${webDir === "." ? "." : webDir}
        run: |
          [ -f package.json ] || echo '{"name":"app","version":"1.0.0","private":true}' > package.json
          npm install --save-exact \\
            @capacitor/cli@6.2.0 \\
            @capacitor/core@6.2.0 \\
            @capacitor/android@6.2.0
          cat > capacitor.config.json << 'CAPEOF'
          {
            "appId": "$PACKAGE_ID",
            "appName": "$APP_NAME",
            "webDir": ".",
            "server": { "androidScheme": "https" }
          }
          CAPEOF

      - name: Adicionar plataforma Android
        working-directory: ${webDir === "." ? "." : webDir}
        run: |
          npx cap add android 2>&1 || true
          npx cap copy android 2>&1
          cp ../release.keystore android/app/release.keystore 2>/dev/null || \\
          cp release.keystore android/app/release.keystore 2>/dev/null || \\
          cp ../../release.keystore android/app/release.keystore || true

      - name: Build APK com Gradle
        working-directory: ${gradleDir}
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease \\
            -Pandroid.injected.signing.store.file=app/release.keystore \\
            -Pandroid.injected.signing.store.password=android123 \\
            -Pandroid.injected.signing.key.alias=app \\
            -Pandroid.injected.signing.key.password=android123 \\
            --no-daemon \\
            --stacktrace 2>&1 | tail -100
          echo "APK gerado com sucesso!"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: "APK-Android-\${{ github.run_number }}"
          path: |
            **/app/build/outputs/apk/release/*.apk
            **/app/build/outputs/apk/debug/*.apk
          if-no-files-found: warn
          retention-days: 30

      - name: Resumo
        run: |
          APK=$(find . -name "*.apk" 2>/dev/null | head -1)
          echo "## \u2705 APK Gerado!" >> $GITHUB_STEP_SUMMARY
          echo "Baixe o arquivo .apk na aba **Artifacts** acima." >> $GITHUB_STEP_SUMMARY
          echo "App: **$APP_NAME** | Package: \`$PACKAGE_ID\`" >> $GITHUB_STEP_SUMMARY
`;
}

/** EAS Cloud workflow — para projetos Expo/React Native.
 *  Usa cloud build do EAS (sem rodar Gradle localmente). */
function genEASWorkflow(): string {
  return `name: "\uD83D\uDE80 Build APK via EAS (Expo)"
on:
  workflow_dispatch:
    inputs:
      expo_token:
        description: "EXPO_TOKEN para autenticar no EAS"
        required: false
        default: ""
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar dependencias
        run: |
          [ -f package-lock.json ] && npm ci || \\
          [ -f yarn.lock ] && yarn install --frozen-lockfile || \\
          [ -f pnpm-lock.yaml ] && npx pnpm install || \\
          npm install

      - name: Instalar EAS CLI
        run: npm install -g eas-cli@latest

      - name: Build APK via EAS Cloud
        run: |
          eas build \\
            --platform android \\
            --profile preview \\
            --non-interactive \\
            --no-wait
          echo "Build enviado para a nuvem EAS!"
        env:
          EXPO_TOKEN: \${{ inputs.expo_token || secrets.EXPO_TOKEN }}

      - name: Instrucoes
        run: |
          echo "## \u23F3 Build no EAS!" >> $GITHUB_STEP_SUMMARY
          echo "Acesse **expo.dev/builds** para baixar o APK (~10 min)." >> $GITHUB_STEP_SUMMARY
`;
}

/** Expo + Capacitor via GitHub Actions — GRÁTIS, sem créditos EAS */
function genExpoCapacitorWorkflow(appName: string, packageId: string, themeColor: string): string {
  const initial = (appName || "A").charAt(0).toUpperCase();
  return `name: "\uD83D\uDCF1 Build APK Android (Capacitor - Grátis)"
on:
  workflow_dispatch:
  push:
    branches: [main, master]
permissions:
  contents: write
env:
  APP_NAME: "${appName.replace(/"/g, '\\"')}"
  PACKAGE_ID: "${packageId}"
  THEME_COLOR: "${themeColor}"
jobs:
  build-apk:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: temurin

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar dependencias
        run: npm install

      - name: Build Expo web
        run: npx expo export --platform web

      - name: Gerar icones com ImageMagick
        run: |
          sudo apt-get install -y imagemagick -q 2>/dev/null
          INIT="${initial}"
          FONT="/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
          [ -f "$FONT" ] || FONT="DejaVu-Sans-Bold"
          gen_icon() {
            SZ=\$1; OUT=\$2
            convert -size \${SZ}x\${SZ} xc:"\$THEME_COLOR" \\
              -fill white -font "\$FONT" \\
              -pointsize \$((\$SZ / 2)) -gravity center \\
              -annotate 0 "\$INIT" "\$OUT" 2>/dev/null || \\
            convert -size \${SZ}x\${SZ} xc:"\$THEME_COLOR" \\
              -fill white -pointsize \$((\$SZ / 2)) -gravity center \\
              -draw "text 0,0 '\$INIT'" "\$OUT" 2>/dev/null || true
          }
          mkdir -p dist
          gen_icon 192 dist/icon-192.png
          gen_icon 512 dist/icon-512.png
          echo "Icones gerados"

      - name: Gerar keystore de assinatura
        run: |
          keytool -genkey -v \\
            -keystore release.keystore -alias app \\
            -keyalg RSA -keysize 2048 -validity 10000 \\
            -storepass android123 -keypass android123 \\
            -dname "CN=\$APP_NAME, OU=App, O=DevMobile, L=BR, ST=SP, C=BR"

      - name: Instalar Capacitor
        run: |
          npm install --save-exact \\
            @capacitor/cli@6.2.0 \\
            @capacitor/core@6.2.0 \\
            @capacitor/android@6.2.0
          cat > capacitor.config.json << 'CAPEOF'
          {
            "appId": "\$PACKAGE_ID",
            "appName": "\$APP_NAME",
            "webDir": "dist",
            "server": { "androidScheme": "https" }
          }
          CAPEOF

      - name: Adicionar plataforma Android
        run: |
          npx cap add android 2>&1 || true
          npx cap copy android 2>&1
          cp release.keystore android/app/release.keystore

      - name: Build APK com Gradle
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease \\
            -Pandroid.injected.signing.store.file=app/release.keystore \\
            -Pandroid.injected.signing.store.password=android123 \\
            -Pandroid.injected.signing.key.alias=app \\
            -Pandroid.injected.signing.key.password=android123 \\
            --no-daemon \\
            --stacktrace 2>&1 | tail -100
          echo "APK gerado com sucesso!"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: "APK-Android-\${{ github.run_number }}"
          path: |
            **/app/build/outputs/apk/release/*.apk
            **/app/build/outputs/apk/debug/*.apk
          if-no-files-found: warn
          retention-days: 30

      - name: Resumo
        run: |
          echo "## \u2705 APK Gerado!" >> \$GITHUB_STEP_SUMMARY
          echo "Baixe o **.apk** na aba **Artifacts** acima." >> \$GITHUB_STEP_SUMMARY
          echo "App: **\$APP_NAME** | Package: \`\$PACKAGE_ID\`" >> \$GITHUB_STEP_SUMMARY
`;
}

/** Deploy GitHub Pages workflow */
function genPagesWorkflow(webDir: string): string {
  const dir = webDir === "." ? "." : webDir;
  return `name: "Deploy GitHub Pages"
on:
  push:
    branches: [main, master]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "${dir}"
      - id: deployment
        uses: actions/deploy-pages@v4
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Component
// ─────────────────────────────────────────────────────────────────────────────

export default function APKBuilderModal({ visible, onClose }: Props) {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  const { activeProject, gitConfigs, settings, updateSettings } = useApp();
  const logScrollRef = useRef<ScrollView>(null);

  const [phase, setPhase] = useState<Phase>("input");
  const [repoInput, setRepoInput] = useState("");
  const [analysis, setAnalysis] = useState<Analysis | null>(null);
  const [logs, setLogs] = useState<string[]>([]);
  const [actionsUrl, setActionsUrl] = useState("");
  const [errorMsg, setErrorMsg] = useState("");
  const [expoTokenInput, setExpoTokenInput] = useState(settings.expoToken || "");
  const [showExpoTokenInput, setShowExpoTokenInput] = useState(false);
  const forceCapacitorRef = useRef(false);

  const ghConfig = gitConfigs.find(g => g.provider === "github");
  const token = ghConfig?.token || "";
  const hasToken = !!token;
  const expoToken = expoTokenInput.trim();

  const addLog = useCallback((msg: string) => {
    setLogs(l => {
      const next = [...l, msg];
      setTimeout(() => logScrollRef.current?.scrollToEnd({ animated: true }), 80);
      return next;
    });
  }, []);

  const reset = () => {
    setPhase("input");
    setAnalysis(null);
    setLogs([]);
    setActionsUrl("");
    setErrorMsg("");
  };

  const handlePaste = useCallback(async () => {
    try {
      const text = await Clipboard.getStringAsync();
      if (text?.trim()) setRepoInput(text.trim());
    } catch { /* ignore */ }
  }, []);

  // ── Analyze ───────────────────────────────────────────────────────────────
  const handleAnalyze = useCallback(async () => {
    const input = repoInput.trim();
    const parsed = input ? parseGithubUrl(input) : null;
    if (!input && (!activeProject || activeProject.files.length === 0)) {
      Alert.alert("Nenhum projeto", "Cole um link do GitHub ou abra um projeto primeiro.");
      return;
    }
    if (input && !parsed) {
      Alert.alert("Link inválido", "Use: https://github.com/usuario/repositorio");
      return;
    }

    setPhase("analyzing");
    setLogs(["🔍 Analisando projeto…"]);

    try {
      let owner = "";
      let repoName = "";
      let fileNames: string[] = [];
      let keyFileContents: Record<string, string> = {};
      let projectFiles: Array<{ path: string; content: string }> = [];

      const KEY_FILES = [
        "app.json", "package.json", "capacitor.config.json",
        "capacitor.config.ts", "index.html", "manifest.json", "vite.config.ts",
        "vite.config.js", "next.config.js", "nuxt.config.js",
      ];

      if (parsed && hasToken) {
        owner = parsed.owner;
        repoName = parsed.repo;
        addLog(`📂 Carregando ${owner}/${repoName}…`);
        const tree = await getRepoTree(token, owner, repoName);
        fileNames = tree.map((f: any) => f.path);
        addLog(`📄 ${fileNames.length} arquivo(s) encontrado(s)`);

        // Load key files for detection
        for (const kf of KEY_FILES) {
          if (fileNames.includes(kf)) {
            try {
              keyFileContents[kf] = await getFileContent(token, owner, repoName, kf);
            } catch { /* skip */ }
          }
        }
      } else if (activeProject) {
        const user = hasToken ? await getUser(token) : null;
        owner = user?.login || "usuario";
        repoName = sanitize(activeProject.name) || "meu-app";
        projectFiles = activeProject.files.map(f => ({
          path: f.path || f.name,
          content: f.content || "",
        }));
        fileNames = projectFiles.map(f => f.path);
        for (const pf of projectFiles) {
          if (KEY_FILES.includes(pf.path)) keyFileContents[pf.path] = pf.content;
        }
        addLog(`📂 Projeto atual: ${activeProject.name}`);
        addLog(`📄 ${fileNames.length} arquivo(s)`);
      }

      // ── Detect method ──────────────────────────────────────────────────────
      let pkgData: any = {};
      let appJsonData: any = {};
      try { pkgData = JSON.parse(keyFileContents["package.json"] || "{}"); } catch { /* ignore */ }
      try { appJsonData = JSON.parse(keyFileContents["app.json"] || "{}"); } catch { /* ignore */ }

      const deps = { ...pkgData.dependencies, ...pkgData.devDependencies };
      const isExpo = !!(appJsonData.expo || deps.expo || deps["expo-router"]);
      const isVite = !!(keyFileContents["vite.config.ts"] || keyFileContents["vite.config.js"]);
      const isCapacitor = fileNames.some(f => f.includes("capacitor.config"));

      let method: BuildMethod;
      let reason: string;
      let preBuildCmd: string | undefined;

      if (isExpo && !forceCapacitorRef.current) {
        method = "eas-cloud";
        reason = "Expo/React Native detectado → EAS Cloud Build (sem Gradle local)";
      } else if (isExpo && forceCapacitorRef.current) {
        method = "capacitor-expo";
        reason = "Expo → Capacitor + GitHub Actions (GRÁTIS, sem créditos EAS)";
      } else if (isVite) {
        method = "capacitor-vite";
        reason = "App Vite/React detectado → Build web + Capacitor Android";
        // detect build command
        const buildScript = pkgData.scripts?.build;
        const hasPnpm = fileNames.includes("pnpm-lock.yaml");
        const mgr = hasPnpm ? "pnpm" : "npm";
        preBuildCmd = `${mgr} install\n          ${mgr} run build`;
      } else {
        method = "capacitor-web";
        reason = isCapacitor
          ? "Capacitor já configurado → Capacitor Android Build"
          : "HTML/JS puro → Capacitor Android Build (sem erros de Gradle)";
      }

      addLog(`✅ Método: ${method}`);
      addLog(`📌 ${reason}`);

      // ── Extract app metadata ───────────────────────────────────────────────
      let appName =
        appJsonData.expo?.name ||
        appJsonData.name ||
        pkgData.name?.replace(/-/g, " ").replace(/\b\w/g, (c: string) => c.toUpperCase()) ||
        activeProject?.name ||
        repoName.replace(/-/g, " ").replace(/\b\w/g, (c: string) => c.toUpperCase()) ||
        "Meu App";

      // clean app name
      appName = appName.replace(/[^\w\s]/g, "").trim() || "Meu App";

      const indexHtml = keyFileContents["index.html"] || "";
      const themeColor = extractColor(indexHtml) ||
        appJsonData.expo?.android?.adaptiveIcon?.backgroundColor ||
        "#0d1117";
      const packageId = appJsonData.expo?.android?.package ||
        toPackageId(owner, repoName);

      // ── Determine webDir ─────────────────────────────────────────────────
      const webDir = method === "capacitor-vite"
        ? (pkgData.scripts?.build?.includes("dist") !== false ? "dist" : ".")
        : ".";

      // ── Build generated files list ────────────────────────────────────────
      const generated: GeneratedFile[] = [];

      if (method !== "eas-cloud") {
        // Main APK workflow
        const wf = method === "capacitor-expo"
          ? genExpoCapacitorWorkflow(appName, packageId, themeColor)
          : genCapacitorWorkflow(appName, packageId, themeColor, webDir, preBuildCmd);
        generated.push({
          path: ".github/workflows/build-apk.yml",
          content: wf,
          label: method === "capacitor-expo"
            ? "Workflow APK (Expo + Capacitor + Gradle) — GRÁTIS"
            : "Workflow APK (Capacitor + Gradle)",
        });

        // GitHub Pages deploy workflow
        generated.push({
          path: ".github/workflows/deploy-pages.yml",
          content: genPagesWorkflow(webDir),
          label: "Workflow GitHub Pages",
        });

        // manifest.json (only if not present or it's web method)
        if (!fileNames.includes("manifest.json")) {
          generated.push({
            path: `${webDir === "." ? "" : webDir + "/"}manifest.json`,
            content: genManifest(appName, themeColor),
            label: "manifest.json (PWA)",
          });
        }

        // icon.svg
        const iconPath = webDir === "." ? "icon.svg" : `${webDir}/icon.svg`;
        if (!fileNames.some(f => f.endsWith("icon.svg") || f.endsWith("icon-192.png"))) {
          generated.push({
            path: iconPath,
            content: genIconSvg(appName, themeColor),
            label: "icon.svg (ícone do app)",
          });
        }

        // service-worker.js
        if (!fileNames.includes("service-worker.js") && !fileNames.includes("sw.js")) {
          const swPath = webDir === "." ? "service-worker.js" : `${webDir}/service-worker.js`;
          generated.push({
            path: swPath,
            content: genServiceWorker(),
            label: "service-worker.js (offline)",
          });
        }

        // capacitor.config.json (only if not present)
        const capConfigPath = webDir === "." ? "capacitor.config.json" : `${webDir}/capacitor.config.json`;
        if (!isCapacitor) {
          generated.push({
            path: capConfigPath,
            content: genCapacitorConfig(appName, packageId, "."),
            label: "capacitor.config.json",
          });
        }

      } else {
        // EAS
        generated.push({
          path: ".github/workflows/build-apk.yml",
          content: genEASWorkflow(),
          label: "Workflow EAS Cloud Build",
        });

        // eas.json if not present
        if (!fileNames.includes("eas.json")) {
          generated.push({
            path: "eas.json",
            content: JSON.stringify({
              cli: { version: ">= 14.0.0", appVersionSource: "local" },
              build: {
                preview: {
                  android: { buildType: "apk", resourceClass: "medium" },
                  distribution: "internal",
                  node: "20.18.0",
                },
                production: {
                  android: { buildType: "app-bundle", resourceClass: "medium" },
                  node: "20.18.0",
                },
              },
            }, null, 2),
            label: "eas.json (perfis de build)",
          });
        }
      }

      // ── Combine with project files ─────────────────────────────────────────
      const generatedPaths = new Set(generated.map(g => g.path));
      const combinedFiles: Array<{ path: string; content: string }> = [];

      // 1. generated files (new/overwrite)
      for (const g of generated) {
        combinedFiles.push({ path: g.path, content: g.content });
      }

      // 2. existing project files (from activeProject, if not from GitHub)
      if (!parsed && activeProject) {
        for (const f of activeProject.files) {
          const fp = f.path || f.name;
          if (!generatedPaths.has(fp)) {
            combinedFiles.push({ path: fp, content: f.content || "" });
          }
        }
      }

      addLog(`📋 ${generated.length} arquivo(s) gerado(s) automaticamente`);
      addLog(`📦 Total para enviar: ${combinedFiles.length} arquivo(s)`);

      setAnalysis({
        method,
        appName,
        repoOwner: owner,
        repoName,
        packageId,
        themeColor,
        reason,
        generated,
        existing: fileNames,
        allFiles: combinedFiles,
      });
      setPhase("review");
    } catch (e: any) {
      setErrorMsg(e.message || String(e));
      setPhase("error");
    }
  }, [repoInput, token, hasToken, activeProject, addLog]);

  // ── Build / Push ─────────────────────────────────────────────────────────
  const handleBuild = useCallback(async () => {
    if (!analysis || !hasToken) return;
    setPhase("building");
    setLogs(["🚀 Iniciando envio para GitHub…"]);
    setActionsUrl("");

    const { repoOwner: owner, repoName: repo, appName, allFiles, method } = analysis;

    try {
      const user = await getUser(token);
      const resolvedOwner = (owner === "usuario" || !owner) ? user.login : owner;
      addLog(`👤 Usuário: ${user.login}`);

      // Salva o token nas settings para uso futuro
      if (expoToken && expoToken !== settings.expoToken) {
        updateSettings({ expoToken });
      }

      // Create repo
      addLog(`📁 Criando repositório "${repo}"…`);
      try {
        await createRepo(token, repo, `${appName} — APK gerado pelo DevMobile`, false);
        addLog("✅ Repositório criado.");
      } catch (e: any) {
        if (e.message?.includes("422") || e.message?.includes("already exists") || e.message?.includes("name already exists")) {
          addLog("ℹ️ Repositório já existe — continuando.");
        } else throw e;
      }

      // For capacitor methods, make repo public for GitHub Pages
      if (method !== "eas-cloud") {
        await makeRepoPublic(token, resolvedOwner, repo).catch(() => {});
        addLog("🌐 Repositório público (para GitHub Pages).");
      }

      // Push all files in chunks
      const CHUNK = 30;
      const chunks: typeof allFiles[] = [];
      for (let i = 0; i < allFiles.length; i += CHUNK) {
        chunks.push(allFiles.slice(i, i + CHUNK));
      }

      addLog(`📤 Enviando ${allFiles.length} arquivo(s) em ${chunks.length} lote(s)…`);
      for (let i = 0; i < chunks.length; i++) {
        await pushFiles(token, resolvedOwner, repo, chunks[i], `${appName} — build APK via DevMobile`);
        addLog(`  ✅ Lote ${i + 1}/${chunks.length} enviado`);
      }

      // Activate GitHub Pages for web methods
      if (method !== "eas-cloud") {
        addLog("🌐 Ativando GitHub Pages…");
        try {
          await enablePages(token, resolvedOwner, repo);
          addLog("✅ GitHub Pages ativado.");
        } catch {
          addLog("ℹ️ GitHub Pages já ativo ou aguardando ativação.");
        }
      }

      const actUrl = `https://github.com/${resolvedOwner}/${repo}/actions`;
      setActionsUrl(actUrl);

      // ── Disparar workflow automaticamente ────────────────────────────
      if (method === "eas-cloud") {
        if (expoToken) {
          addLog("");
          addLog("🚀 Disparando workflow EAS automaticamente…");
          await new Promise(r => setTimeout(r, 4000));
          try {
            await dispatchWorkflow(
              token, resolvedOwner, repo,
              "build-apk.yml",
              { expo_token: expoToken }
            );
            addLog("✅ Workflow disparado! Build iniciado no EAS.");
          } catch (e2: any) {
            addLog(`⚠️  Disparo automático falhou: ${e2.message}`);
            addLog("   Vá em GitHub → Actions e dispare manualmente.");
          }
        } else {
          addLog("");
          addLog("⚠️  Sem EXPO_TOKEN — dispare manualmente em Actions.");
        }
      } else if (method === "capacitor-expo") {
        addLog("");
        addLog("🚀 Disparando workflow Capacitor automaticamente…");
        await new Promise(r => setTimeout(r, 4000));
        try {
          await dispatchWorkflow(token, resolvedOwner, repo, "build-apk.yml", {});
          addLog("✅ Build iniciado! GitHub Actions está construindo o APK.");
          addLog("⏳ Pronto em ~15 min — GRÁTIS, sem créditos EAS.");
        } catch (e2: any) {
          addLog(`⚠️  Disparo automático falhou: ${e2.message}`);
          addLog("   Vá em GitHub → Actions e clique em Run workflow.");
        }
      }

      addLog("");
      addLog("═══════════════════════════════════");
      addLog("✅ CONCLUÍDO!");
      if (method === "eas-cloud") {
        addLog("⏳ APK pronto em ~10 min em expo.dev/builds");
      } else {
        addLog("⏳ APK pronto em ~15 min em Artifacts");
      }
      addLog("═══════════════════════════════════");

      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
      setPhase("done");
    } catch (e: any) {
      setErrorMsg(e.message || String(e));
      setPhase("error");
    }
  }, [analysis, token, hasToken, expoToken, settings.expoToken, updateSettings, addLog]);

  // ── Method metadata ───────────────────────────────────────────────────────
  const methodInfo = (m: BuildMethod) => {
    switch (m) {
      case "eas-cloud": return { label: "EAS Cloud Build", color: "#3b82f6", icon: "cloud" as const };
      case "capacitor-vite": return { label: "Capacitor + Vite Build", color: "#f97316", icon: "zap" as const };
      case "capacitor-expo": return { label: "Capacitor + GitHub Actions — GRÁTIS", color: "#22c55e", icon: "gift" as const };
      default: return { label: "Capacitor Android Build", color: "#22c55e", icon: "smartphone" as const };
    }
  };

  return (
    <Modal visible={visible} animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}>
      <View style={[s.root, { backgroundColor: colors.background }]}>

        {/* ── Header ── */}
        <View style={[s.header, { borderBottomColor: colors.border, paddingTop: insets.top + 8 }]}>
          <View style={{ flexDirection: "row", alignItems: "center", gap: 10 }}>
            <View style={{ width: 32, height: 32, borderRadius: 10, backgroundColor: "#f9731622", alignItems: "center", justifyContent: "center" }}>
              <Feather name="smartphone" size={16} color="#f97316" />
            </View>
            <View>
              <Text style={[s.title, { color: colors.foreground }]}>Gerar APK Android</Text>
              <Text style={[s.subtitle, { color: colors.mutedForeground }]}>
                {phase === "input"      ? "Cole o repo ou use o projeto aberto" :
                 phase === "analyzing"  ? "Analisando projeto…" :
                 phase === "review"     ? "Revisão — tudo gerado automaticamente" :
                 phase === "building"   ? "Enviando para o GitHub…" :
                 phase === "done"       ? "✅ Enviado! APK em construção" :
                                          "❌ Erro"}
              </Text>
            </View>
          </View>
          <TouchableOpacity onPress={onClose} hitSlop={{ top:10, bottom:10, left:10, right:10 }}>
            <Feather name="x" size={22} color={colors.mutedForeground} />
          </TouchableOpacity>
        </View>

        <ScrollView
          ref={logScrollRef}
          contentContainerStyle={{ padding: 16, gap: 14, paddingBottom: insets.bottom + 40 }}
        >

          {/* ══════════ INPUT ══════════ */}
          {phase === "input" && (
            <>
              {!hasToken && (
                <View style={[s.alertBox, { backgroundColor: "#f59e0b11", borderColor: "#f59e0b44" }]}>
                  <Feather name="alert-triangle" size={14} color="#f59e0b" />
                  <Text style={{ color: "#f59e0b", fontSize: 12, flex: 1 }}>
                    Configure o token GitHub em Menu → GitHub para usar todos os recursos.
                  </Text>
                </View>
              )}

              <Text style={[s.label, { color: colors.mutedForeground }]}>LINK DO REPOSITÓRIO GITHUB</Text>
              <Text style={{ color: colors.mutedForeground, fontSize: 12, marginTop: -8 }}>
                Deixe em branco para usar o projeto aberto no editor.
              </Text>

              <View style={{ flexDirection: "row", gap: 8 }}>
                <TextInput
                  style={[s.input, { flex: 1, color: colors.foreground, borderColor: colors.border, backgroundColor: colors.card }]}
                  value={repoInput}
                  onChangeText={setRepoInput}
                  placeholder="https://github.com/usuario/meu-app"
                  placeholderTextColor={colors.mutedForeground + "77"}
                  autoCapitalize="none"
                  autoCorrect={false}
                />
                <TouchableOpacity
                  onPress={handlePaste}
                  style={{ paddingHorizontal: 14, justifyContent: "center", backgroundColor: colors.card, borderRadius: 10, borderWidth: 1, borderColor: colors.border }}
                >
                  <Feather name="clipboard" size={16} color={colors.primary} />
                </TouchableOpacity>
              </View>

              {activeProject && !repoInput && (
                <View style={[s.infoRow, { backgroundColor: colors.card, borderColor: colors.border }]}>
                  <Feather name="folder" size={13} color={colors.primary} />
                  <Text style={{ color: colors.foreground, fontSize: 12, flex: 1 }}>
                    Projeto atual: <Text style={{ fontWeight: "700" }}>{activeProject.name}</Text>
                    {"  "}<Text style={{ color: colors.mutedForeground }}>({activeProject.files.length} arquivo{activeProject.files.length !== 1 ? "s" : ""})</Text>
                  </Text>
                </View>
              )}

              {/* ── EXPO_TOKEN ── */}
              <Text style={[s.label, { color: colors.mutedForeground, marginTop: 4 }]}>EXPO TOKEN (EAS BUILD)</Text>
              <View style={{ flexDirection: "row", gap: 8, alignItems: "center" }}>
                <TextInput
                  style={[s.input, { flex: 1, color: colors.foreground, borderColor: expoTokenInput ? colors.primary : colors.border, backgroundColor: colors.card }]}
                  value={expoTokenInput}
                  onChangeText={setExpoTokenInput}
                  placeholder="Cole seu token aqui — expo.dev → Access Tokens"
                  placeholderTextColor={colors.mutedForeground + "88"}
                  autoCapitalize="none"
                  autoCorrect={false}
                  secureTextEntry={!showExpoTokenInput}
                />
                <TouchableOpacity
                  onPress={async () => {
                    try {
                      const t = await Clipboard.getStringAsync();
                      if (t?.trim()) setExpoTokenInput(t.trim());
                    } catch { /* ignore */ }
                  }}
                  style={{ paddingHorizontal: 12, paddingVertical: 11, backgroundColor: colors.card, borderRadius: 10, borderWidth: 1, borderColor: colors.border }}
                >
                  <Feather name="clipboard" size={16} color={colors.primary} />
                </TouchableOpacity>
                <TouchableOpacity
                  onPress={() => setShowExpoTokenInput(v => !v)}
                  style={{ paddingHorizontal: 10, paddingVertical: 11 }}
                >
                  <Feather name={showExpoTokenInput ? "eye-off" : "eye"} size={16} color={colors.mutedForeground} />
                </TouchableOpacity>
              </View>
              {expoTokenInput ? (
                <View style={{ flexDirection: "row", alignItems: "center", gap: 6, backgroundColor: "#22c55e11", borderRadius: 8, padding: 8, borderWidth: 1, borderColor: "#22c55e33" }}>
                  <Feather name="zap" size={12} color="#22c55e" />
                  <Text style={{ color: "#22c55e", fontSize: 12 }}>Build será disparado automaticamente após o envio!</Text>
                </View>
              ) : (
                <Text style={{ color: colors.mutedForeground, fontSize: 11 }}>
                  Sem token: você dispara manualmente em GitHub → Actions.
                </Text>
              )}

              {/* What gets generated */}
              <View style={[s.card, { backgroundColor: colors.card, borderColor: colors.border }]}>
                <Text style={[s.label, { color: colors.mutedForeground, marginBottom: 8 }]}>O QUE SERÁ GERADO AUTOMATICAMENTE</Text>
                {[
                  ["✅", "manifest.json + ícone SVG + service worker"],
                  ["✅", "capacitor.config.json com ID e nome do app"],
                  ["✅", "Workflow GitHub Actions (sem erros de Gradle)"],
                  ["✅", "Keystore de assinatura gerada no CI"],
                  ["✅", "Deploy automático no GitHub Pages"],
                ].map(([icon, text]) => (
                  <View key={text} style={{ flexDirection: "row", gap: 8, marginBottom: 4 }}>
                    <Text style={{ fontSize: 12 }}>{icon}</Text>
                    <Text style={{ color: colors.foreground, fontSize: 12, flex: 1 }}>{text}</Text>
                  </View>
                ))}
              </View>

              <TouchableOpacity
                onPress={() => { forceCapacitorRef.current = false; handleAnalyze(); }}
                style={[s.bigBtn, { backgroundColor: colors.primary }]}
                activeOpacity={0.8}
              >
                <Feather name="search" size={18} color="#fff" />
                <Text style={{ color: "#fff", fontWeight: "700", fontSize: 16 }}>Analisar e Preparar Tudo</Text>
              </TouchableOpacity>

              <TouchableOpacity
                onPress={() => { forceCapacitorRef.current = true; handleAnalyze(); }}
                style={[s.bigBtn, { backgroundColor: "#22c55e22", borderWidth: 1.5, borderColor: "#22c55e66" }]}
                activeOpacity={0.8}
              >
                <Feather name="gift" size={18} color="#22c55e" />
                <View style={{ flex: 1 }}>
                  <Text style={{ color: "#22c55e", fontWeight: "700", fontSize: 15 }}>Gerar APK GRÁTIS (Capacitor)</Text>
                  <Text style={{ color: "#22c55e99", fontSize: 11 }}>GitHub Actions — sem créditos EAS</Text>
                </View>
              </TouchableOpacity>
            </>
          )}

          {/* ══════════ ANALYZING ══════════ */}
          {phase === "analyzing" && (
            <View style={[s.logBox, { backgroundColor: "#000", borderColor: colors.border }]}>
              <ScrollView>
                {logs.map((l, i) => (
                  <Text key={i} style={s.logText}>{l}</Text>
                ))}
                <View style={{ flexDirection: "row", alignItems: "center", gap: 6, marginTop: 6 }}>
                  <ActivityIndicator size="small" color="#22c55e" />
                  <Text style={{ color: "#22c55e88", fontSize: 12 }}>Analisando…</Text>
                </View>
              </ScrollView>
            </View>
          )}

          {/* ══════════ REVIEW ══════════ */}
          {phase === "review" && analysis && (() => {
            const mi = methodInfo(analysis.method);
            return (
              <View style={{ gap: 12 }}>

                {/* Analysis log */}
                <View style={[s.logBox, { backgroundColor: "#000", borderColor: colors.border, maxHeight: 100 }]}>
                  <ScrollView>
                    {logs.map((l, i) => (
                      <Text key={i} style={s.logText}>{l}</Text>
                    ))}
                  </ScrollView>
                </View>

                {/* Method badge */}
                <View style={[s.infoRow, { backgroundColor: mi.color + "15", borderColor: mi.color + "44" }]}>
                  <Feather name={mi.icon} size={16} color={mi.color} />
                  <View style={{ flex: 1, gap: 2 }}>
                    <Text style={{ color: mi.color, fontWeight: "700", fontSize: 13 }}>{mi.label}</Text>
                    <Text style={{ color: colors.mutedForeground, fontSize: 11 }}>{analysis.reason}</Text>
                  </View>
                </View>

                {/* App details */}
                <View style={[s.card, { backgroundColor: colors.card, borderColor: colors.border }]}>
                  <Text style={[s.label, { color: colors.mutedForeground, marginBottom: 8 }]}>DETALHES DO APP</Text>
                  {[
                    ["App", analysis.appName],
                    ["Repositório", `${analysis.repoOwner}/${analysis.repoName}`],
                    ["Package ID", analysis.packageId],
                    ["Cor do tema", analysis.themeColor],
                  ].map(([k, v]) => (
                    <View key={k} style={{ flexDirection: "row", justifyContent: "space-between", paddingVertical: 5, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }}>
                      <Text style={{ color: colors.mutedForeground, fontSize: 12 }}>{k}</Text>
                      <Text style={{ color: colors.foreground, fontSize: 12, fontWeight: "600", maxWidth: "60%", textAlign: "right" }} numberOfLines={1}>{v}</Text>
                    </View>
                  ))}
                </View>

                {/* Generated files list */}
                <View style={[s.card, { backgroundColor: colors.card, borderColor: colors.border }]}>
                  <Text style={[s.label, { color: colors.mutedForeground, marginBottom: 8 }]}>
                    {analysis.generated.length} ARQUIVO(S) GERADO(S) AUTOMATICAMENTE
                  </Text>
                  {analysis.generated.map(f => (
                    <View key={f.path} style={{ flexDirection: "row", alignItems: "flex-start", gap: 8, marginBottom: 6 }}>
                      <View style={{ width: 18, height: 18, borderRadius: 4, backgroundColor: "#22c55e22", alignItems: "center", justifyContent: "center", marginTop: 1 }}>
                        <Feather name="file-plus" size={10} color="#22c55e" />
                      </View>
                      <View style={{ flex: 1 }}>
                        <Text style={{ color: colors.foreground, fontSize: 11, fontFamily: "monospace" }} numberOfLines={1}>{f.path}</Text>
                        <Text style={{ color: colors.mutedForeground, fontSize: 10 }}>{f.label}</Text>
                      </View>
                    </View>
                  ))}
                </View>

                {/* EAS token status */}
                {analysis.method === "eas-cloud" && (
                  <>
                    {expoToken ? (
                      <View style={[s.alertBox, { backgroundColor: "#22c55e11", borderColor: "#22c55e44" }]}>
                        <Feather name="check-circle" size={14} color="#22c55e" />
                        <Text style={{ color: "#22c55e", fontSize: 12, flex: 1, lineHeight: 18 }}>
                          <Text style={{ fontWeight: "700" }}>EXPO_TOKEN salvo!</Text> Após o envio, toque no botão para adicionar automaticamente ao repositório GitHub.
                        </Text>
                      </View>
                    ) : (
                      <View style={[s.alertBox, { backgroundColor: "#f59e0b11", borderColor: "#f59e0b44" }]}>
                        <Feather name="alert-triangle" size={14} color="#f59e0b" />
                        <Text style={{ color: "#f59e0b", fontSize: 12, flex: 1, lineHeight: 18 }}>
                          Configure seu <Text style={{ fontWeight: "700" }}>EXPO_TOKEN</Text> em Config → EAS Build para build automático.
                        </Text>
                      </View>
                    )}
                    <TouchableOpacity
                      onPress={() => { forceCapacitorRef.current = true; handleAnalyze(); }}
                      style={[s.alertBox, { backgroundColor: "#22c55e11", borderColor: "#22c55e44", gap: 8 }]}
                      activeOpacity={0.7}
                    >
                      <Feather name="gift" size={14} color="#22c55e" />
                      <Text style={{ color: "#22c55e", fontSize: 12, flex: 1 }}>
                        <Text style={{ fontWeight: "700" }}>Sem créditos EAS?</Text> Toque aqui para trocar para Capacitor (GRÁTIS via GitHub Actions)
                      </Text>
                      <Feather name="chevron-right" size={14} color="#22c55e" />
                    </TouchableOpacity>
                  </>
                )}

                {!hasToken && (
                  <View style={[s.alertBox, { backgroundColor: "#ef444411", borderColor: "#ef444433" }]}>
                    <Feather name="alert-circle" size={14} color="#f87171" />
                    <Text style={{ color: "#f87171", fontSize: 12, flex: 1 }}>
                      Token GitHub necessário para enviar. Configure em Menu → GitHub.
                    </Text>
                  </View>
                )}

                <TouchableOpacity
                  onPress={handleBuild}
                  disabled={!hasToken}
                  style={[s.bigBtn, { backgroundColor: hasToken ? "#22c55e" : colors.secondary }]}
                  activeOpacity={0.8}
                >
                  <Feather name="zap" size={18} color={hasToken ? "#fff" : colors.mutedForeground} />
                  <Text style={{ color: hasToken ? "#fff" : colors.mutedForeground, fontWeight: "700", fontSize: 16 }}>
                    Enviar e Empacotar APK
                  </Text>
                </TouchableOpacity>

                <TouchableOpacity onPress={reset} style={{ alignItems: "center", paddingVertical: 8 }}>
                  <Text style={{ color: colors.mutedForeground, fontSize: 12 }}>↩ Voltar</Text>
                </TouchableOpacity>
              </View>
            );
          })()}

          {/* ══════════ BUILDING ══════════ */}
          {phase === "building" && (
            <View style={[s.logBox, { backgroundColor: "#000", borderColor: colors.border }]}>
              <ScrollView ref={logScrollRef}>
                {logs.map((l, i) => (
                  <Text key={i} style={s.logText}>{l}</Text>
                ))}
                <View style={{ flexDirection: "row", alignItems: "center", gap: 6, marginTop: 6 }}>
                  <ActivityIndicator size="small" color="#22c55e" />
                  <Text style={{ color: "#22c55e88", fontSize: 12 }}>Enviando…</Text>
                </View>
              </ScrollView>
            </View>
          )}

          {/* ══════════ DONE ══════════ */}
          {phase === "done" && (
            <View style={{ gap: 12 }}>
              <View style={[s.infoRow, { backgroundColor: "#22c55e15", borderColor: "#22c55e44" }]}>
                <Feather name="check-circle" size={16} color="#22c55e" />
                <Text style={{ color: "#4ade80", fontWeight: "700", fontSize: 13, flex: 1 }}>
                  Tudo enviado! GitHub está construindo o APK…
                </Text>
              </View>

              <View style={[s.logBox, { backgroundColor: "#000", borderColor: colors.border, maxHeight: 200 }]}>
                <ScrollView>
                  {logs.map((l, i) => (
                    <Text key={i} style={s.logText}>{l}</Text>
                  ))}
                </ScrollView>
              </View>

              {/* EAS: links pós-build */}
              {analysis?.method === "eas-cloud" && (
                <View style={{ gap: 8 }}>
                  {expoToken ? (
                    <View style={[s.infoRow, { backgroundColor: "#22c55e15", borderColor: "#22c55e44" }]}>
                      <Feather name="zap" size={14} color="#22c55e" />
                      <Text style={{ color: "#4ade80", fontSize: 12, flex: 1, fontWeight: "600" }}>
                        Workflow disparado automaticamente! APK em ~10 min.
                      </Text>
                    </View>
                  ) : (
                    <View style={[s.alertBox, { backgroundColor: "#f59e0b11", borderColor: "#f59e0b44" }]}>
                      <Feather name="alert-triangle" size={14} color="#f59e0b" />
                      <Text style={{ color: "#f59e0b", fontSize: 12, flex: 1 }}>
                        Token não informado — dispare manualmente em GitHub → Actions.
                      </Text>
                    </View>
                  )}
                  <TouchableOpacity
                    onPress={() => Linking.openURL("https://expo.dev/builds")}
                    style={[s.bigBtn, { backgroundColor: "#7c3aed22", borderColor: "#7c3aed66", borderWidth: 1 }]}
                    activeOpacity={0.75}
                  >
                    <Feather name="package" size={18} color="#a78bfa" />
                    <View style={{ flex: 1 }}>
                      <Text style={{ color: "#a78bfa", fontWeight: "700", fontSize: 14 }}>Acompanhar no expo.dev/builds</Text>
                      <Text style={{ color: colors.mutedForeground, fontSize: 11 }}>Baixe o APK quando terminar (~10 min)</Text>
                    </View>
                    <Feather name="external-link" size={14} color={colors.mutedForeground} />
                  </TouchableOpacity>
                </View>
              )}

              {actionsUrl && (
                <TouchableOpacity
                  onPress={() => Linking.openURL(actionsUrl)}
                  style={[s.bigBtn, { backgroundColor: "#3b82f622", borderColor: "#3b82f644", borderWidth: 1 }]}
                  activeOpacity={0.75}
                >
                  <Feather name="git-branch" size={18} color="#60a5fa" />
                  <View style={{ flex: 1 }}>
                    <Text style={{ color: "#60a5fa", fontWeight: "700", fontSize: 14 }}>Abrir Actions no GitHub</Text>
                    <Text style={{ color: colors.mutedForeground, fontSize: 11 }}>Baixe o APK em Artifacts quando terminar</Text>
                  </View>
                  <Feather name="external-link" size={14} color={colors.mutedForeground} />
                </TouchableOpacity>
              )}

              <View style={[s.card, { backgroundColor: colors.card, borderColor: colors.border }]}>
                <Text style={[s.label, { color: colors.mutedForeground, marginBottom: 6 }]}>INSTALAR O APK NO CELULAR</Text>
                <Text style={{ color: colors.foreground, fontSize: 12, lineHeight: 20 }}>
                  1. Baixe o arquivo <Text style={{ fontWeight: "700" }}>.apk</Text> dos Artifacts{"\n"}
                  2. No celular: Configurações → Segurança{"\n"}
                  3. Ative <Text style={{ fontWeight: "700" }}>Fontes desconhecidas</Text>{"\n"}
                  4. Abra o .apk e instale
                </Text>
              </View>

              <TouchableOpacity onPress={reset} style={{ alignItems: "center", paddingVertical: 8 }}>
                <Text style={{ color: colors.mutedForeground, fontSize: 12 }}>↩ Gerar outro APK</Text>
              </TouchableOpacity>
            </View>
          )}

          {/* ══════════ ERROR ══════════ */}
          {phase === "error" && (
            <View style={{ gap: 12 }}>
              <View style={[s.infoRow, { backgroundColor: "#ef444415", borderColor: "#ef444444" }]}>
                <Feather name="alert-circle" size={16} color="#f87171" />
                <Text style={{ color: "#f87171", fontSize: 12, flex: 1, lineHeight: 18 }}>{errorMsg}</Text>
              </View>
              <TouchableOpacity onPress={reset} style={[s.bigBtn, { backgroundColor: colors.secondary }]} activeOpacity={0.8}>
                <Feather name="refresh-cw" size={16} color={colors.foreground} />
                <Text style={{ color: colors.foreground, fontWeight: "700", fontSize: 15 }}>Tentar novamente</Text>
              </TouchableOpacity>
            </View>
          )}

        </ScrollView>
      </View>
    </Modal>
  );
}

const s = StyleSheet.create({
  root: { flex: 1 },
  header: {
    flexDirection: "row", alignItems: "center", justifyContent: "space-between",
    paddingHorizontal: 16, paddingBottom: 12, borderBottomWidth: StyleSheet.hairlineWidth,
  },
  title: { fontSize: 16, fontWeight: "700" },
  subtitle: { fontSize: 11, marginTop: 1 },
  label: { fontSize: 10, fontWeight: "700", letterSpacing: 1, textTransform: "uppercase" },
  input: { borderWidth: 1, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10, fontSize: 14 },
  infoRow: {
    flexDirection: "row", alignItems: "flex-start", gap: 10,
    borderWidth: 1, borderRadius: 12, padding: 12,
  },
  alertBox: {
    flexDirection: "row", alignItems: "flex-start", gap: 8,
    borderWidth: 1, borderRadius: 10, padding: 10,
  },
  card: { borderWidth: 1, borderRadius: 12, padding: 12 },
  bigBtn: {
    flexDirection: "row", alignItems: "center", justifyContent: "center",
    gap: 10, borderRadius: 14, padding: 16,
  },
  logBox: { borderWidth: 1, borderRadius: 10, padding: 10, minHeight: 80, maxHeight: 280 },
  logText: { color: "#22c55e", fontSize: 11, fontFamily: "monospace", lineHeight: 18 },
});
